### PR TITLE
Test JSON serialization of xarray

### PR DESCRIPTION
**Pull request by padraic-shafer**
@martintb  In the spirit of testing changes, I'm suggesting a test case that would have caught this previously.

~The only catch is that it exposes [some other potential issues](https://github.com/bluesky/tiled/issues/515#issuecomment-1694700386) that might need to be resolved first.~  With your update ~AND the changes suggested in that comment,~ this new test passes.

@danielballan  Would you prefer another way of handling this? (No problem if it involves ignoring my suggestion to include this test.)

[_Strikeouts added on Aug. 29, 2023_]

### CODE REVIEW

**Comment by martintb** [comment]
Linking #560

I think a test makes perfect sense and I learned some things about pytest by reading your test!  I'll merge this as soon as I get a go ahead from Dan or whomever else reviews the PR. 

Question though: Is there a reason that that you put `ImportError` guardrails on the test? That doesn't seem to be a pattern in the rest of the tiled test suite.

**Comment by padraic-shafer** [comment]
The import guard is there because `serialize_json()` gets defined for xarray only if the `orjson` module is available in the environment.

https://github.com/bluesky/tiled/blob/b3564569db8b80672a8e75583817e5b9f8e3a927/tiled/serialization/xarray.py#L95-L103

**Comment by danielballan** [comment]
Thanks both. I agree tests are needed here.

For simplicity, I would rather remove the conditionality and just always run the test. In a testing context, we are not so concerned with supporting a minimal subject of dependencies. (We make exceptions for tests that require external _services_ like a Postgres database or an LDAP server.)

**Comment by padraic-shafer** [comment]
I'll simplify the test module then, and push the changes shortly.

**Comment by padraic-shafer** [comment]
~Note that this test still fails because of [additional changes that appear to be needed](https://github.com/bluesky/tiled/issues/515#issuecomment-1694701894) to make the call to `serialize_json()` more robust.  Those changes might have knock on effects, and will need another set of eyes.~

[_Strikeouts added on Aug. 29, 2023._  This was my misunderstanding of the expected parameter type for `serialize_json()`.]

**Comment by padraic-shafer** [comment]
This test has been updated based on [feedback](https://github.com/bluesky/tiled/pull/561#issuecomment-1698147163) about the intended usage of `serialize_json()`.

@danielballan If this looks good to you, I think it's ready for @martintb to pull in this test; then for you to merge #560 to correct that typo.

**Comment by padraic-shafer** [comment]
I went back and cleaned up comments above to (hopefully) avoid confusing us when we look back on this in a year or two.

**Review by danielballan — APPROVED** [review]

**Comment by danielballan** [comment]
Thanks. Ready for an alley-oop with @martintb. Merge away!

**Comment by martintb** [comment]
Thanks @padraic-shafer and @danielballan! Merged!

**Pull request merged**
